### ISSUE TITLE
CopyCustomResource | CREATE_FAILED | Response object is too long.

### ISSUE THREAD

**Issue by ZacharyRSmith** [aws-samples/amazon-cloudfront-secure-static-site#23]
when i first deployed, a nested stack err'd with
```
CopyCustomResource | CREATE_FAILED | Response object is too long.
-- | -- | --
```

i successfully deployed after replacing www/ with www/index.html where index.html is just 'hi'.

i think CopyCustomResource was hitting the 4kb limit. I think it's trying to copy all of www/ in 1 go:
```
  CopyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../www
      Environment:
        Variables:
          BUCKET: !Ref S3BucketRoot
      Handler: witch.staticHandler
      Layers:
        - !Ref CopyLayerVersion
      Role: !GetAtt CopyRole.Arn
      Runtime: nodejs12.x
      Timeout: 300
```

but of course my www/ will have >4kb.

i was able to comment out CopyCustomResource and run an aws s3 sync outside cloudformation. But is there a way to do this inside cloudformation when www/ >4kb?
