### ISSUE TITLE
Invalid request provided: AWS::CloudFront::OriginAccessControl

### ISSUE THREAD

**Issue by thomasleplus** [aws-samples/amazon-cloudfront-secure-static-site#66]
I merged PR #65 into my private repo but when I run the CloudFormation stack, I get the following error:

```
Resource handler returned message: "Invalid request provided: AWS::CloudFront::OriginAccessControl" (RequestToken: <REDACTED>, HandlerErrorCode: InvalidRequest)
```

The error doesn't give much information but a quick web search indicates that InvalidRequest are usually caused by syntax errors in the CF template. So I ran cfn-lint on my template and I get no error. I've tried adding a description to the OriginAccessControl in case it's not optional despite what the doc say. That didn't help. Any suggestion would be greatly appreciated.

This is my YAML in case I am missed something during the merge:

```yaml
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub 'oac-${AWS::StackName}-${AWS::Region}'
        Description: !Sub 'CloudFront OAC for ${Subdomain}.${DomainName}'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
```

**Comment by ConnorKirk** [comment]
Thanks for opening an issue. I've recreated it.

I will investigate to find the cause.

**Comment by thomasleplus** [comment]
Hi @ConnorKirk,

Shortening the OAC config name did the trick!

I went with using the subdomain and domain name instead of the stack name because it's short enough and unique enough for my use case:

```
OriginAccessControlConfig:
  Name: !Sub
    - 'oac-${Subdomain}-${DashedDomainName}'
    - DashedDomainName: !Join ['-', !Split ['.', !Ref DomainName]]
```

Thanks!

**Comment by thomasleplus** [comment]
As far as I am concerned this issue is resolved. If others have the same issue, I am happy to make a PR with my changes but I am not sure if my solution above would work for everyone (for example what if someone doesn't use a subdomain).

**Comment by ConnorKirk** [comment]
Thanks @thomasleplus 

Glad to hear you have resolved your issue. I'm still considering the best resolution for users of the sample. I'm working on PR to fix the issue. Once that is merged I will close this. I'll keep it open in the mean time in case another user encounters the same problem.

**Comment by ConnorKirk** [comment]
Fixed in #69

**Comment by ConnorKirk** [comment]
In the end I used the Stack ID, as this is constant length, but different in each stack. thank you for your help in identifying and resolving the issue.

Here's the relevant snippet in case it is helpful.

```yaml
 Name: !Sub
          - amzn-secure-static-site-${guid}
          - guid: !Select [2, !Split ['/', !Ref 'AWS::StackId']]
 ```
